# Generated by Django 4.2.3 on 2023-09-13 23:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.IntegerField(default=0)),
                ("ultima_actualizacion", models.DateField()),
                ("frecuencia_actualizaciones", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mes_Imputacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Residente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("apodo", models.CharField(default="sin apodo", max_length=50)),
                ("dni", models.IntegerField(default=0)),
                (
                    "email",
                    models.EmailField(
                        default="laflordelbambuapp@gmail.com", max_length=254
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=datetime.datetime.now)),
                ("ingreso", models.IntegerField(default=0)),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Incomes.cuota"
                    ),
                ),
                (
                    "mes",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Incomes.mes_imputacion",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Incomes.residente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cuota",
            name="residente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Incomes.residente"
            ),
        ),
    ]
