# Generated by Django 4.2.3 on 2023-10-05 19:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "apodo",
                    models.CharField(
                        default="sin apodo", max_length=50, verbose_name="Apodo"
                    ),
                ),
                ("dni", models.IntegerField(default=0, verbose_name="Dni")),
                (
                    "email",
                    models.EmailField(
                        default="laflordelbambuapp@gmail.com",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "ingreso",
                    models.IntegerField(default="", verbose_name="Ingreso de dinero"),
                ),
                (
                    "mes",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes de imputacion",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MinValueValidator(2020),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Año de imputacion",
                    ),
                ),
                (
                    "residente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Incomes.residente",
                        verbose_name="Residente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.IntegerField(default=0, verbose_name="Precio")),
                (
                    "ultima_actualizacion",
                    models.DateField(verbose_name="Ultima Actualizacion"),
                ),
                (
                    "frecuencia_actualizaciones",
                    models.IntegerField(verbose_name="Frecuencia Actualizaciones"),
                ),
                (
                    "residente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Incomes.residente",
                        verbose_name="Residente",
                    ),
                ),
            ],
        ),
    ]
