# Generated by Django 4.2.3 on 2023-09-14 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Incomes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingreso",
            name="anio",
            field=models.IntegerField(
                default=2023,
                validators=[
                    django.core.validators.MinValueValidator(2020),
                    django.core.validators.MaxValueValidator(2030),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="mes",
            field=models.IntegerField(
                default=9,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Mes_Imputacion",
        ),
    ]
