# Generated by Django 4.2.3 on 2023-07-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Incomes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
    ]
