# Generated by Django 4.2.3 on 2023-09-28 05:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Incomes", "0002_ingreso_anio_alter_ingreso_mes_delete_mes_imputacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingreso",
            name="cuota",
        ),
        migrations.AlterField(
            model_name="cuota",
            name="frecuencia_actualizaciones",
            field=models.IntegerField(verbose_name="Frecuencia Actualizaciones"),
        ),
        migrations.AlterField(
            model_name="cuota",
            name="precio",
            field=models.IntegerField(default=0, verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="cuota",
            name="residente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Incomes.residente",
                verbose_name="Residente",
            ),
        ),
        migrations.AlterField(
            model_name="cuota",
            name="ultima_actualizacion",
            field=models.DateField(verbose_name="Ultima Actualizacion"),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="anio",
            field=models.IntegerField(
                default=2023,
                validators=[
                    django.core.validators.MinValueValidator(2020),
                    django.core.validators.MaxValueValidator(2030),
                ],
                verbose_name="Año de imputacion",
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="fecha",
            field=models.DateField(default=datetime.datetime.now, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="ingreso",
            field=models.IntegerField(default="", verbose_name="Ingreso de dinero"),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="mes",
            field=models.IntegerField(
                default=9,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mes de imputacion",
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="residente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Incomes.residente",
                verbose_name="Residente",
            ),
        ),
        migrations.AlterField(
            model_name="residente",
            name="apellido",
            field=models.CharField(max_length=50, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="residente",
            name="apodo",
            field=models.CharField(
                default="sin apodo", max_length=50, verbose_name="Apodo"
            ),
        ),
        migrations.AlterField(
            model_name="residente",
            name="dni",
            field=models.IntegerField(default=0, verbose_name="Dni"),
        ),
        migrations.AlterField(
            model_name="residente",
            name="email",
            field=models.EmailField(
                default="laflordelbambuapp@gmail.com",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="residente",
            name="nombre",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
    ]
