# Generated by Django 4.2.3 on 2023-07-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Incomes", "0003_cuota_ingreso_residente_remove_income_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="residente",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
